apiVersion: rbac.authorization.vector.io/v1
kind: ClusterRole
metadata:
  name: office-crole
rules:
  - apiVersion: core.vector.io
    resources:
      - NodeGroup
    resouseNames:
      - office-01
    verbs:
      - get
      - list
      - watch
  - apiVersion: core.vector.io
    resources:
      - Application
    resourceNames:
      - "*"
    verbs:
      - get
      - list
      - watch